language: python
python:
  - "3.6.3"
install:
  - bash tests/travis_install.sh
script:
  - hass -c . --script check_config
before_install:
  - mv tests/travis_secrets.yaml secrets.yaml

cache:
  directories:
    - $HOME/.cache/pip
