id: turn_off_garage_exterior_lights_at_dawn
alias: Turn off Garage Exterior Lights at Dawn
trigger:
  - platform: state
    entity_id: sun.sun
    to: 'above_horizon'
action:
  - service: switch.turn_off
    entity_id: switch.zooz_unknown_typeb111_id1e1c_switch
