###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/05/2018
#  @package      :  Amar And Guest Bathroom Fans
#  @description  :  Controls bathroom fans for both Amar's and the guest rooms.
#                   Includes timers and synchronizes with the roof extraction
#                   fan.
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'amar_and_guest_bathroom_fans'

      timer_defaults: &timer_defaults
        duration: 1200

    input_number.amar_roof_extraction_fan_users:
      <<: *customize

    timer.amar_bathroom_fan_timer:
      <<: *customize
    timer.guest_bathroom_fan_timer:
      <<: *customize

    automation.activate_amars_bathroom_fan_timer:
      <<: *customize
    automation.deactivate_amars_bathroom_fan_timer:
      <<: *customize
    automation.deactivate_amars_bathroom_fan_when_timer_finishes:
      <<: *customize
    automation.activate_guest_bathroom_fan_timer:
      <<: *customize
    automation.deactivate_guest_bathroom_fan_timer:
      <<: *customize
    automation.deactivate_guest_bathroom_fan_when_timer_finishes:
      <<: *customize
    automation.increment_amars_roof_extraction_fan_users:
      <<: *customize
    automation.decrement_amars_roof_extraction_fan_users:
      <<: *customize
    automation.activate_amars_roof_extraction_fan:
      <<: *customize
    automation.deactivate_amars_roof_extraction_fan:
      <<: *customize

input_number:
  amar_roof_extraction_fan_users:
    name: Amar's Roof Extraction Fan Users
    min: 0
    max: 2
    step: 1

timer:
  amar_bathroom_fan_timer:
    name: Amar's Bathroom Fan Timer
    <<: *timer_defaults

  guest_bathroom_fan_timer:
    name: Guest Bathroom Fan Timer
    <<: *timer_defaults

################################################
## Automation
################################################

automation:
  ################################################
  ## Amar's Bathroom Fan & Timer
  ################################################

  - id: activate_amars_bathroom_fan_timer
    alias: Activate Amar's Bathroom Fan Timer
    trigger:
      - platform: state
        entity_id: switch.amar_bathroom_fan
        to: 'on'
    action:
      - service: timer.start
        entity_id: timer.amar_bathroom_fan_timer
        data:
          <<: *timer_defaults

  - id: deactivate_amars_bathroom_fan_timer
    alias: Deactivate Amar's Bathroom Fan Timer
    trigger:
      - platform: state
        entity_id: switch.amar_bathroom_fan
        to: 'off'
    action:
      - service: timer.cancel
        entity_id: timer.amar_bathroom_fan_timer

  - id: deactivate_amars_bathroom_fan_when_timer_finishes
    alias: Deactivate Amar's Bathroom Fan when Timer Finishes
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.amar_bathroom_fan_timer
    action:
      - service: switch.turn_off
        entity_id: switch.amar_bathroom_fan

  ################################################
  ## Guest Bathroom Fan & Timer
  ################################################

  - id: activate_guest_bathroom_fan_timer
    alias: Activate Guest Bathroom Fan Timer
    trigger:
      - platform: state
        entity_id: switch.guest_bathroom_fan
        to: 'on'
    action:
      - service: timer.start
        entity_id: timer.guest_bathroom_fan_timer
        data:
          <<: *timer_defaults

  - id: deactivate_guest_bathroom_fan_timer
    alias: Deactivate Guest Bathroom Fan Timer
    trigger:
      - platform: state
        entity_id: switch.guest_bathroom_fan
        to: 'off'
    action:
      - service: timer.cancel
        entity_id: timer.guest_bathroom_fan_timer

  - id: deactivate_guest_bathroom_fan_when_timer_finishes
    alias: Deactivate Guest Bathroom Fan when Timer Finishes
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.guest_bathroom_fan_timer
    action:
      - service: switch.turn_off
        entity_id: switch.guest_bathroom_fan

  ################################################
  ## Amar's Roof Extraction Fan
  ################################################

  - id: increment_amars_roof_extraction_fan_users
    alias: Increment Amar's Roof Extraction Fan Users
    trigger:
      - platform: state
        entity_id:
          - switch.amar_bathroom_fan
          - switch.guest_bathroom_fan
        to: 'on'
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.amar_roof_extraction_fan_users
          value: >
            {% if states('input_number.amar_roof_extraction_fan_users') | int
                < state_attr('input_number.amar_roof_extraction_fan_users', 'max') %}
              {{ (states('input_number.amar_roof_extraction_fan_users') | int) + 1 }}
            {% else %}
              {{ states('input_number.amar_roof_extraction_fan_users') | int }}
            {% endif %}

  - id: decrement_amars_roof_extraction_fan_users
    alias: Decrement Amar's Roof Extraction Fan Users
    trigger:
      - platform: state
        entity_id:
          - switch.amar_bathroom_fan
          - switch.guest_bathroom_fan
        to: 'off'
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.amar_roof_extraction_fan_users
          value: >
            {% if states('input_number.amar_roof_extraction_fan_users') | int
                > state_attr('input_number.amar_roof_extraction_fan_users', 'min') %}
              {{ (states('input_number.amar_roof_extraction_fan_users') | int) - 1 }}
            {% else %}
              {{ states('input_number.amar_roof_extraction_fan_users') | int }}
            {% endif %}

  - id: activate_amars_roof_extraction_fan
    alias: Activate Amar's Roof Extraction Fan
    trigger:
      - platform: state
        entity_id: input_number.amar_roof_extraction_fan_users
    action:
      - service: switch.turn_on
        entity_id: switch.amar_roof_extraction_fan
    condition:
      - condition: numeric_state
        entity_id: input_number.amar_roof_extraction_fan_users
        value_template: "{{ states('input_number.amar_roof_extraction_fan_users') | int }}"
        above: 0

  - id: deactivate_amars_roof_extraction_fan
    alias: Deactivate Amar's Roof Extraction Fan
    trigger:
      - platform: state
        entity_id: input_number.amar_roof_extraction_fan_users
    action:
      - service: switch.turn_off
        entity_id: switch.amar_roof_extraction_fan
    condition:
      - condition: numeric_state
        entity_id: input_number.amar_roof_extraction_fan_users
        value_template: "{{ states('input_number.amar_roof_extraction_fan_users') | int }}"
        below: 1
