---
automation:
  - id: 28dd9f30-e3e5-4071-900c-3a15a30fc16f
    alias: Manage the Family Room Roller Shades
    description: Automatically open/close the Family Room Roller Shades based on the Sun Position
    triggers:
      - trigger: sun
        event: sunset
      - trigger: sun
        event: sunrise
        offset: '+4:00:00'
      - trigger: homeassistant
        event: start
      - trigger: event
        event_type: automation_reloaded
    actions:
      - choose:
          - alias: If it's after sunset or before sunrise, then close the shades.
            conditions:
              - condition: or
                conditions:
                  - condition: sun
                    after: sunset
                  - condition: sun
                    before: sunrise
                    before_offset: '+1:30:00'
            sequence:
              # - wait_template: "{{ is_state('binary_sensor.living_room_windows', 'off') }}"
              - action: cover.close_cover
                target:
                  entity_id: cover.family_room_shades
          - alias: If it's 4 hours after sunrise, then open the shade.
            conditions:
              - condition: sun
                after: sunrise
                after_offset: '+4:00:00'
            sequence:
              - action: cover.open_cover
                target:
                  entity_id: cover.family_room_shades
    mode: single

  - id: 316fabab-021e-4da1-8aee-c5d865a5552c
    alias: Manage the Family Room Lights
    triggers:
      - trigger: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: -5.0
      - trigger: homeassistant
        event: start
      - trigger: event
        event_type: automation_reloaded
      - trigger: time
        at: "01:00:00"
    actions:
      - choose:
          - alias: If the sun is low enough, then turn on the family room center lights.
            conditions:
              - condition: numeric_state
                entity_id: sun.sun
                attribute: elevation
                below: -5.0
              - condition: time
                after: "12:00:00"
            sequence:
              - action: light.turn_on
                target:
                  entity_id: light.family_room_ceiling_lights_center
                data:
                  brightness_pct: 100
        default:
          - action: light.turn_off
            target:
              entity_id: light.family_room_ceiling_lights_center
