###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  07/20/2024
#  @package      :  Guest Room
#  @description  :  Manages devices in the Guest Room
###############################################################################
---
automation:
  - id: 6841223b-9711-4581-b2ee-60c0278cfede
    alias: Control Guest Room Closet Lights
    description: Utilizes the motion_light blueprint for controlling the Guest Room Closet Lights.
    use_blueprint:
      path: rohankapoorcom/motion_light.yaml
      input:
        motion_entity: binary_sensor.guest_room_closet_door
        light_target: light.guest_room_closet_lights
        no_motion_wait: 0

  - id: 657a280f-0bd6-4126-9003-a2c56fade359
    alias: Control Guest Bathroom Heater
    description: Syncs the State of the Inovelli Light Switch with the Guest Bathroom Heater.
    triggers:
      - trigger: state
        entity_id: switch.guest_bathroom_floor_heater_switch
        id: "switch_state_changed"
      - trigger: state
        entity_id: climate.guest_bathroom_heater
        id: "climate_state_changed"
    actions:
      - choose:
          - conditions:
              - condition: trigger
                id: "switch_state_changed"
            sequence:
              - if:
                  - condition: state
                    entity_id: switch.guest_bathroom_floor_heater_switch
                    state: "on"
                then:
                  - action: climate.turn_on
                    entity_id: climate.guest_bathroom_heater
                else:
                  - action: climate.turn_off
                    entity_id: climate.guest_bathroom_heater
          - conditions:
              - condition: trigger
                id: "climate_state_changed"
            sequence:
              - if:
                  - condition: state
                    entity_id: climate.guest_bathroom_heater
                    state: heat
                then:
                  - action: switch.turn_on
                    entity_id: switch.guest_bathroom_floor_heater_switch
                else:
                  - action: switch.turn_off
                    entity_id: switch.guest_bathroom_floor_heater_switch
