###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/12/2018
#  @package      :  HA System
#  @description  :  Manages aspects of the home assistant system. If the travis
#                   build succeeds (on the master branch), it will update the
#                   local configuration and then check if a HA update is
#                   required (in the repo) and the process the update,
#                   restarting HA when complete.
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'ha_system'

      defaults: &defaults
        scan_interval: 10

      command_line_sensor_default: &command_line_sensor_defaults
        <<: *defaults
        command_timeout: 5

    ################################################
    ## Sensor
    ################################################

    sensor.rohankapoorcom_003_homeassistant_config_last_build_state:
      <<: *customize

    sensor.current_git_commit_id:
      <<: *customize

    sensor.current_git_commit_time:
      <<: *customize

    sensor.current_version:
      <<: *customize

    sensor.desired_version:
      <<: *customize

    sensor.upgraded_version:
      <<: *customize

    ################################################
    ## Automation
    ################################################

    automation.update_configuration_if_travis_build_is_successful:
      <<: *customize

    ################################################
    ## Shell Command
    ################################################

    shell_command.git_pull:
      <<: *customize

    shell_command.update_homeassistant:
      <<: *customize

    ################################################
    ## Script
    ################################################

    script.pull_and_restart_homeassistant:
      <<: *customize

    script.update_homeassistant:
      <<: *customize

################################################
## Sensor
################################################

command_line:
  - sensor:
    <<: *command_line_sensor_defaults
    name: current_git_commit_id
    command: '/usr/bin/git -C /etc/homeassistant/ rev-parse HEAD'
    unique_id: b2baf567-afb8-4b44-a1ee-1a9db7f03c9e

  - sensor:
    <<: *command_line_sensor_defaults
    name: current_git_commit_time
    command: '/usr/bin/git -C /etc/homeassistant/ log -1 --format="%at" | /usr/bin/xargs -I{} /bin/date -ud @{} +"%Y-%m-%dT%H:%M:%S.000Z"'
    unique_id: 70e009eb-38f2-4bc7-b757-3a2f819833d6

  - sensor:
    <<: *command_line_sensor_defaults
    name: desired_version
    command: '/bin/cat /etc/homeassistant/.HA_VERSION'
    unique_id: b598c94e-04c9-4d7a-94eb-4dc5fb6e61f4

  - sensor:
    <<: *command_line_sensor_defaults
    name: upgraded_version
    command: '/srv/homeassistant/bin/hass --version'
    unique_id: 815960ce-f440-4cb8-b0f1-d55da809feee

################################################
## Automation
################################################

# automation:

#   - id: update_configuration_if_travis_build_is_successful
#     alias: Update configuration if travis build is successful
#     trigger:
#       - entity_id: sensor.rohankapoorcom_003_homeassistant_config_last_build_state
#         platform: state
#         to: 'passed'
#     condition:
#       - condition: template
#         value_template: "{{ is_state_attr('sensor.rohankapoorcom_003_homeassistant_config_last_build_state', 'Commit Branch', 'master') }}"
#       - condition: template
#         value_template: "{{ not is_state_attr('sensor.rohankapoorcom_003_homeassistant_config_last_build_state', 'Commit SHA', states('sensor.current_git_commit_id')) }}"
#       - condition: template
#         value_template: "{{ states('sensor.current_git_commit_time') < state_attr('sensor.rohankapoorcom_003_homeassistant_config_last_build_state', 'Committed Date') }}"
#     action:
#       - service: script.pull_and_restart_homeassistant

################################################
## Shell Command
################################################

shell_command:
  git_pull: "/usr/bin/git -C /etc/homeassistant/ pull"
  update_homeassistant: "/bin/bash /etc/homeassistant/bash_scripts/update.sh -u {{ states('sensor.desired_version') }}"

################################################
## Script
################################################

script:

  pull_and_restart_homeassistant:
    sequence:
      - service: shell_command.git_pull
      - wait_template: "{{ is_state_attr('sensor.rohankapoorcom_003_homeassistant_config_last_build_state', 'Commit SHA', states('sensor.current_git_commit_id')) }}"
      - delay:
          seconds: 30 # Wait for all command line sensors to be updated
      - service: script.update_homeassistant
      - wait_template: "{{ is_state('sensor.upgraded_version', states('sensor.desired_version')) }}"
      - service: homeassistant.restart

  update_homeassistant:
    sequence:
      - condition: template
        value_template: "{{ states('sensor.current_version') < states('sensor.desired_version') }}"
      - service: shell_command.update_homeassistant
