###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  12/31/2023
#  @package      :  Hallway
#  @description  :  Manages devices in the hallway
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'hallway'

################################################
## Automation
################################################
automation:
  - id: a0c79981-25ad-4b1c-b6de-c18e2fd0ceed
    alias: Manage the Hallway Lights
    triggers:
      - trigger: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: -5.0
      - trigger: homeassistant
        event: start
      - trigger: event
        event_type: automation_reloaded
      - trigger: time
        at: "00:00:00"
    actions:
      - choose:
          - alias: If the sun is low enough, then turn on the hallway lights.
            conditions:
              - condition: numeric_state
                entity_id: sun.sun
                attribute: elevation
                below: -5.0
              - condition: time
                after: "12:00:00"
            sequence:
              - action: light.turn_on
                target:
                  entity_id: light.hallway_lights
                data:
                  brightness_pct: 100
        default:
          - action: light.turn_off
            target:
              entity_id: light.hallway_lights

  - id: 09ed178f-72c6-432e-9902-eeafb87c04b8
    alias: Control Hallway Closet Lights
    description: Utilizes the motion_light blueprint for controlling the Closet Lights in the Hallway.
    use_blueprint:
      path: rohankapoorcom/motion_light.yaml
      input:
        motion_entity: binary_sensor.hallway_closet_door
        light_target: light.hallway_closet_lights
        no_motion_wait: 0
