###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  01/19/2026
#  @package      :  Kitchen
#  @description  :  Logic for handling items in the kitchen.
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'kitchen'

################################################
## Sensor
################################################
template:
  - trigger:
      - platform: state
        entity_id: sensor.dishwasher_power
      - platform: time_pattern
        minutes: "/1"
    sensor:
      - name: Dishwasher Power Sampled
        unique_id: 21499c92-79e0-4e6b-9343-968861f5df3f
        unit_of_measurement: W
        device_class: power
        state_class: measurement
        state: "{{ states('sensor.dishwasher_power') | float(0) }}"

sensor:
  - platform: statistics
    name: Dishwasher Power Max 5min
    unique_id: e4ad4893-48fb-4024-8077-620b68b35b87
    entity_id: sensor.dishwasher_power_sampled
    state_characteristic: value_max
    max_age:
      minutes: 5
    sampling_size: 300
    keep_last_sample: true

################################################
## Script
################################################
script:
  update_dishwasher_display:
    use_blueprint:
      path: rohankapoorcom/update-dishwasher-epaper-display.yaml
      input:
        epaper_tag: d15e08d4c5a9d613bd7f9295cfadf8e7

################################################
## Automation
################################################
automation:
  - id: fbd7a7ca-eb6b-45c4-b536-27138e95810d
    alias: Update Dishwasher Display
    description: "Set Dishwasher Display status based on power usage"
    use_blueprint:
      path: >-
        sbyx/notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes.yaml
      input:
        power_sensor: sensor.dishwasher_power_max_5min
        starting_threshold: 50
        finishing_threshold: 15
        actions:
          - action: script.update_dishwasher_display
            data:
              state: Clean
        starting_hysteresis: 2
        finishing_hysteresis: 10
        pre_actions:
          - action: script.update_dishwasher_display
            data:
              state: Running

  - id: 819098b7-0743-41fa-aeb2-468d7aeebd03
    alias: Dishwasher Display Button Triggers
    description: Change the dishwasher display based on buttons triggered
    use_blueprint:
      path: rohankapoorcom/solum-m3-epaper-tag-buttons.yaml
      input:
        epaper_tag:
          - d15e08d4c5a9d613bd7f9295cfadf8e7
        button_1:
          - action: script.update_dishwasher_display
            data:
              state: Clean
        button_2:
          - action: script.update_dishwasher_display
            data:
              state: Dirty
