###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/11/2018
#  @package      :  Library
#  @description  :  Controls library lighting
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'library'

    automation.toggle_library_lights:
      <<: *customize

################################################
## Automation
################################################

automation:

  - id: toggle_library_lights
    alias: Toggle Library Lights
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.hank_unknown_type0201_id000b
          scene_id: 3
          scene_data: 0
    action:
      - service: switch.toggle
        entity_id: switch.zooz_unknown_typeb111_id1e1c_switch_4
