###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  12/23/2024
#  @package      :  Living Room
#  @description  :  Manages devices in the Living ROom
###############################################################################
---
automation:
  - id: 3a0dc198-d275-46ff-a588-54a2375d1c34
    alias: Control Living Room Lamp
    description: Syncs the State of the Inovelli Light Switch with the Living Room Lamp.
    triggers:
      - trigger: state
        entity_id: light.living_room_lights
    actions:
      - if:
          - condition: state
            entity_id: light.living_room_lights
            state: "on"
        then:
          - action: light.turn_on
            entity_id: light.living_room_lamp
        else:
          - action: light.turn_off
            entity_id: light.living_room_lamp
    mode: restart
    max_exceeded: silent