###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  05/31/2024
#  @package      :  Master Bedrooms
#  @description  :  Automations in the Master Bedroom
###############################################################################
---
################################################
## Fan
################################################
fan:
  - trigger: template
    fans:
      master_bedroom_fan:
        friendly_name: Master Bedroom Fan
        unique_id: 9d34e6d1-58fc-4feb-8499-fc397483dcaf
        value_template: "{{is_state('light.master_bedroom_fan', 'on')}}"
        percentage_template: >
          {{ (state_attr('light.master_bedroom_fan', 'brightness') | float(0) * 0.392)  | round(0)}}
        turn_on:
          action: light.turn_on
          target:
            entity_id:
              - light.master_bedroom_fan
        turn_off:
          action: light.turn_off
          target:
            entity_id:
              - light.master_bedroom_fan
        set_percentage:
          action: light.turn_on
          data:
            brightness_pct: "{{ percentage }}"
          target:
            entity_id:
              - light.master_bedroom_fan
        speed_count: 3

################################################
## Automation
################################################
automation:
  - id: 919f9df7-9160-47c1-b854-9db94174bcc7
    alias: Adjust the Master Bedroom Default Brightness
    description: Utilizes a blueprint to configure the default brightess on the Master Bedroom Lights.
    use_blueprint:
      path: rohankapoorcom/inovelli-red-series-night-mode.yaml
      input:
        zwave_device: 942407d971d64b514e0bc7cb9ff644cb
        bedtime: '21:00:00'
        bedtime_brightness: 2
        wakeup_time: '08:00:00'
        wakeup_time_brightness: 99

  - id: a223a1d3-8aa7-4ec2-85b6-7c8538b561b0
    alias: Master Bedroom Remote Controls
    description: "Utilizes a blueprint to control the light and fan in the Master Bedroom via remote."
    use_blueprint:
      path: rwalker777/Zen37-ZwaveJS-blueprint.yaml
      input:
        zen37lr:
          - 0fa34d93a7b489fd964767762d2b36c1
        button_1_1_tap:
          - action: light.toggle
            target:
              entity_id: light.master_bedroom_lights
        button_2_1_tap:
          - action: fan.toggle
            target:
              entity_id: fan.master_bedroom_fan
        button_3_1_tap:
          - action: fan.decrease_speed
            target:
              entity_id: fan.master_bedroom_fan
        button_4_1_tap:
          - action: fan.increase_speed
            target:
              entity_id: fan.master_bedroom_fan
