###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  10/14/2018
#  @package      :  Outdoors
#  @description  :  Manages outdoor lighting
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'outdoors'

    ################################################
    ## Automation
    ################################################

    automation.turn_on_garage_exterior_lights_at_dusk:
      <<: *customize

    automation.turn_off_garage_exterior_lights_at_dawn:
      <<: *customize

################################################
## Automation
################################################
automation:

  - id: turn_on_garage_exterior_lights_at_dusk
    alias: Turn on Garage Exterior Lights at Dusk
    trigger:
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
    action:
    - service: switch.turn_on
      entity_id: switch.garage_exterior_lights

  - id: turn_off_garage_exterior_lights_at_dawn
    alias: Turn off Garage Exterior Lights at Dawn
    trigger:
    - platform: state
      entity_id: sun.sun
      to: 'above_horizon'
    action:
    - service: switch.turn_off
      entity_id: switch.garage_exterior_lights
