###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  10/14/2018
#  @package      :  Outdoors
#  @description  :  Manages outdoor lighting
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'outdoors'

################################################
## Automation
################################################
automation:

  - id: eb962a09-eb64-4a54-bd9f-a8ee12e1493c
    alias: Manage the Garage Exterior Lights
    triggers:
      - trigger: state
        entity_id: sun.sun
        to: 'below_horizon'
      - trigger: state
        entity_id: sun.sun
        to: 'above_horizon'
      - trigger: homeassistant
        event: start
      - trigger: event
        event_type: automation_reloaded
    actions:
      - choose:
          - alias: If it's after sunset or before sunrise, then turn on the lights.
            conditions:
              - condition: or
                conditions:
                  - condition: sun
                    after: sunset
                    after_offset: "-0:15:00"
                  - condition: sun
                    before: sunrise
            sequence:
              - action: light.turn_on
                target:
                  entity_id: light.garage_exterior_lights
          - alias: If it's after sunrise, then turn off the lights.
            conditions:
              - condition: sun
                after: sunrise
            sequence:
              - action: light.turn_off
                target:
                  entity_id: light.garage_exterior_lights

  - id: 28dc8832-551c-461a-b3d8-e2cb02c4a817
    alias: Notify that the shed heater is on
    description: Use Inovelli light switch LED indicators to notify the user that the shed heater is on.
    mode: single
    triggers:
      - trigger: state
        entity_id: switch.shed_heater
      - trigger: homeassistant
        event: start
      - trigger: event
        event_type: automation_reloaded
    actions:
      - choose:
          - conditions:
              - condition: state
                entity_id: switch.shed_heater
                state: "on"
            sequence:
              - action: script.inovelli_led
                data:
                  label: backyard
                  duration: Forever
                  effect: Blink Fast
                  color: Red
                  brightness: 10
        default:
          - action: script.inovelli_led
            data:
              label: backyard
              duration: Forever
              effect: Clear Effect
              color: Red
              brightness: 10

  - id: 2453b77a-30be-441b-a355-74a77268b768
    alias: Manage the Front Door Exterior Lights
    triggers:
      - trigger: state
        entity_id: sun.sun
        to: 'below_horizon'
      - trigger: state
        entity_id: sun.sun
        to: 'above_horizon'
      - trigger: homeassistant
        event: start
      - trigger: event
        event_type: automation_reloaded
    actions:
      - choose:
          - alias: If it's after sunset or before sunrise, then turn on the lights.
            conditions:
              - condition: or
                conditions:
                  - condition: sun
                    after: sunset
                    after_offset: "-0:15:00"
                  - condition: sun
                    before: sunrise
            sequence:
              - action: light.turn_on
                target:
                  entity_id: light.front_door_exterior_lights
          - alias: If it's after sunrise, then turn off the lights.
            conditions:
              - condition: sun
                after: sunrise
            sequence:
              - action: light.turn_off
                target:
                  entity_id: light.front_door_exterior_lights

  - id: ec2ae516-1e3d-4134-9f2a-6d67c12d7de9
    alias: Manage the Garden Exterior Lights
    triggers:
      - trigger: state
        entity_id: sun.sun
        to: 'below_horizon'
      - trigger: state
        entity_id: sun.sun
        to: 'above_horizon'
      - trigger: homeassistant
        event: start
      - trigger: event
        event_type: automation_reloaded
    actions:
      - choose:
          - alias: If it's after sunset or before sunrise, then turn on the lights.
            conditions:
              - condition: or
                conditions:
                  - condition: sun
                    after: sunset
                    after_offset: "-0:15:00"
                  - condition: sun
                    before: sunrise
            sequence:
              - action: light.turn_on
                target:
                  entity_id:
                    - light.exterior_lights_cherry_tree
                    - light.exterior_lights_maple_tree
                    - light.exterior_lights_driveway_end
                    - light.exterior_lights_walkway_lights
                    - light.exterior_lights_bay_window_conifers
                    - light.exterior_lights_forsythia_bed
                    - light.exterior_lights_back_woods
          - alias: If it's after sunrise, then turn off the lights.
            conditions:
              - condition: sun
                after: sunrise
            sequence:
              - action: light.turn_off
                target:
                  entity_id:
                    - light.exterior_lights_cherry_tree
                    - light.exterior_lights_maple_tree
                    - light.exterior_lights_driveway_end
                    - light.exterior_lights_walkway_lights
                    - light.exterior_lights_bay_window_conifers
                    - light.exterior_lights_forsythia_bed
                    - light.exterior_lights_back_woods

  - id: c1789adb-ff1e-424d-8b85-65f307bf995d
    alias: Control the Garage Lights
    mode: restart
    max_exceeded: silent
    triggers:
      - trigger: homeassistant
        event: start
      - trigger: event
        event_type: automation_reloaded
      - trigger: state
        entity_id: cover.anu_garage_door
        from: 'closed'
        to: 'open'
      - trigger: state
        entity_id: cover.rakesh_garage_door
        from: 'closed'
        to: 'open'
    action:
      - choose:
          - alias: If either garage door is open, then turn on the lights.
            conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: cover.anu_garage_door
                    state: 'open'
                  - condition: state
                    entity_id: cover.rakesh_garage_door
                    state: 'open'
            sequence:
              - action: light.turn_on
                target:
                  entity_id:
                    - light.garage_lights
              - wait_for_trigger:
                  - platform: template
                    value_template: >
                      {{ is_state('cover.anu_garage_door', 'closed')
                      and is_state('cover.rakesh_garage_door', 'closed') }}
                continue_on_timeout: false
              - delay:
                  minutes: 10
              - service: light.turn_off
                target:
                  entity_id:
                    - light.garage_lights
        default:
          - service: light.turn_off
            entity_id:
              - light.garage_lights
