###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  10/14/2018
#  @package      :  Security
#  @description  :  Controls cameras, locks and other security devices
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'security'

camera:
  - platform: ffmpeg
    name: Fish 1
    input: !secret camera.ffmpeg.fish1.input

amcrest: !secret amcrest

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

stream:
