###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  10/14/2018
#  @package      :  Security
#  @description  :  Controls cameras, locks and other security devices
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'security'

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

stream:
