---
name: Check Config

# yamllint disable-line rule:truthy
on:
  push:

  pull_request:
    branches: [master]

jobs:

  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Check out configuration from GitHub
        uses: actions/checkout@v4
      - name: Run yamllint
        uses: frenck/action-yamllint@v1
  home-assistant:
    name: Home Assistant Config Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out configuration from GitHub
        uses: actions/checkout@v4
      - name: Run Home Assistant Core Configuration Check
        uses: frenck/action-home-assistant@v1
        with:
          secrets: tests/travis_secrets.yaml
